AI4OPT/PGLearn.jl

Project.toml

Not much changes in Clarabel v0.9 since v0.7, except they improved numerical stability in [v0.8](https://github.com/oxfordcontrol/Clarabel.jl/releases/tag/v0.8.0)

Bump Clarabel compat --> v0.9

---

src/utils/json.jl
test/io.jl

Additional unit tests for
* Conversion of complex number type to `Complex{Float64}` with potential loss of precision when saving HDF5 files
* JSON file I/O which was previously untested

Additional I/O tests

---

exp/config.toml
src/OPFGenerator.jl
src/opf/ed.jl
src/opf/opf.jl
src/sampler/reserve.jl
src/sampler/sampler.jl
test/io.jl
test/opf/ed.jl
test/opf/opf.jl
test/runtests.jl
test/sampler.jl

Adds the EconomicDispatch formulation, to match the [E2ELR paper](https://arxiv.org/abs/2304.11726).
Todo:
---
New formulation checklist:
---
In `exp/config.toml`:
In `src/opf/opf.jl`:
In `src/opf/<opf>.jl`:
In `test/opf/opf.jl`:
In `test/opf/<opf>.jl`:
In `test/sampler.jl`:

Economic Dispatch formulation

---

src/opf/ed.jl
test/opf/ed.jl

1. Export bound duals separately
1. Removes the non-existent slack upper bounds

Export bound duals separately in EconomicDispatch

---

src/sampler/reserve.jl

Reserve bounds were messed up since iterating over a dictionary doesn't preserve order.
Also, makes sure `rmax ≤ pmax`.

Fix dictionary iteration in reserve sampler

---

.github/workflows/doc_cleanup.yml
README.md
docs/make.jl
docs/src/io.md
docs/src/lib/public.md
src/OPFGenerator.jl
src/utils/hdf5.jl
src/utils/json.jl

To check this locally:
```bash
julia --project=docs -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate(); include("docs/make.jl");'
```
Then render the `docs/build/index.html` to browse the documentation locally.

Add starter Manual and Reference sections to the docs

---

README.md
exp/config.toml
exp/sampler.jl
src/opf/acp.jl
src/opf/dcp.jl
src/opf/ed.jl
src/opf/opf.jl
src/opf/socwr.jl
test/opf/acp.jl
test/opf/dcp.jl
test/opf/opf.jl
test/opf/socwr.jl
test/runtests.jl
test/sampler.jl

This PR introduces our own type system:
`PM.AbstractPowerModel -> AbstractFormulation`
`PM.ACPPowerModel -> ACOPF`
`PM.DCPPowerModel -> DCOPF`
`PM.SOCWRConicPowerModel -> SOCOPF`
`PM.SOCWRPowerModel -> SOCOPFQuad`

Replace types

---

exp/config.toml
src/opf/ed.jl
src/opf/opf.jl
test/io.jl
test/opf/ed.jl
test/opf/opf.jl
test/runtests.jl
test/sampler.jl

This PR updates the EconomicDispatch implementation:
- Add reserve bounds + MRR to OPFData
- Separate types for ED/EDR
- No soft power balance or soft reserve requirement option
- Remove `export_ptdf`
Todo:

EconomicDispatch with OPFData

---

src/opf/acp.jl
src/opf/dcp.jl
src/opf/ed.jl
src/opf/opf.jl
src/opf/socwr.jl
test/opf/opf.jl
test/opf/utils.jl
test/runtests.jl

Current state only changes the `OPFData` struct and parsers. 
Still need to update
[EDIT]: the ED branch will need to update the `solve!` code, which currently uses bus-level demand data.

Load-level information

---

exp/config.toml
exp/sampler.jl
slurm/make_ref.jl
slurm/merge.jl
slurm/submit_jobs.jl

Update SLURM pipeline

---

exp/config.toml
exp/sampler.jl
slurm/make_ref.jl
slurm/merge.jl
slurm/submit_jobs.jl
src/OPFGenerator.jl
src/config.jl
test/sampler.jl

This (draft) PR modifies the structure of the config file and data-generation scripts to support datasets beyond PGLib cases.
**The core feature I want is the ability to generate data given an arbitrary, user-provided Matpower file.** (see #131)
The current code uses a `"ref"` key in the config file to load the corresponding PGLib case using the `PGLib` package.
This prevents us from generating data based on anything that's not PGLib.
This branch replaces the config key `ref` with _two_ keys:
* `case_file`: path to Matpower case; data-generation will error if path is not valid.
* `case_name`: this effectively replaces the `"ref"` we had before
The reason for adding `case_name` is that we currently use `config["ref"]` not only to load data, but also in file naming conventions and for some …

Provide case file in config 

---

src/sampler/load.jl
test/sampler.jl

This PR modifies the existing `LoadScaler` to sample noise for both active and reactive loads, which allows to have non-constant power factors. There is no change to the user-facing APIs, but the behavior obviously changes

P-Q load sampling

---

README.md

The CI badge displayed "no status" for an unknown reason, so I changed the URL.
Also added a badge with a link to our (latest) documentation, which is otherwise hard to find.

Fix CI badge, add docs badge

---

src/opf/utils.jl

Fixes #146
Small change to how we report primal/dual objective values.
Before: we check `has_values` and `has_duals`, and return `objective_value` and `dual_objective_value` accordingly. If a model doesn't have a primal/dual solution, we report `Inf` (primal) and `-Inf` (dual).
After: in addition to checking `has_values` and `has_duals`, we check whether the solution status is either `FEASIBLE_POINT`, `NEARLY_FEASIBLE_POINT`, or `INFEASIBLE_POINT`. If both conditions are met, then we return `objective_value` and `dual_objective_value` accordingly. Otherwise, we return a `NaN` value.
A couple notes: 
* primal/dual are checked separately, i.e., there may be a primal objective value but no dual objective value
* there is no change to the export of the primal/dual solution itself: if a …

Add safeguards for querying primal/dual objective value

---

docs/definitions.jl
docs/make.jl
docs/src/assets/definitions.tex
docs/src/assets/wider.css
docs/src/opf/acp.md
docs/src/opf/dcp.md

This branch continues from `mt/ac-docs`:
- Switch to `MathJax3` (`MathJax` is deprecated)
- Utility functions for reusing our `definitions.tex` file
- Slightly widened the `docs-main` div so the labels fit
- Updated AC docs
- Updated DC docs
Note this version doesn't have the corresponding dual next to each constraint / in the data table.
https://ai4opt.github.io/OPFGenerator/previews/PR153/opf/acp/

Update AC/DC docs

---

docs/make.jl
docs/src/assets/redlinks.css

The Mathjax default "SVG" renderer overrides the link color to `blue`, which is hard to read when in dark mode:
This PR changes the link color to `red`, which is easier to read:
ref https://github.com/mathjax/MathJax/issues/2485
https://ai4opt.github.io/OPFGenerator/previews/PR160

Red links for legibility in dark mode

---

docs/src/opf/acp.md
docs/src/opf/dcp.md
docs/src/opf/socwr.md
src/opf/acp.jl
src/opf/dcp.jl
src/opf/ed.jl
src/opf/socwr.jl
test/opf/socwr.jl

Merging dual variables associated to two-sided constraints, most typically showing up as lower/upper bound on primal variables.
This should reduce the size of datasets on disk (and in memory)

Merge duals of lower/upper bound constraints

---

exp/sampler.jl
slurm/make_ref.jl
slurm/merge.jl
test/sampler.jl

Addresses #166 
While doing this, I realized that our H5 sorting/de-duplicating helper functions assume an input dictionary that contains a valid `["meta"]["seed"]` key. 
The present changes (removing `"meta"` from the root of the input data dictionary) no longer satisfy that assumption when dealing with input data.
I had two ways around this issue:
1. manually add a `["meta"]["seed"]` key to the input data dictionary, process, then remove that key
2. update the lower-level functions to not require a `["meta"]["seed"]` key
I chose the first one because it required the least amount of code 😅

Do not re-export config in input.h5

---

docs/src/opf/socwr.md

- Fix typo
- Fix errors such as incorrect description of constraints and variable key that doesn't match the description
- Fix some notations and LaTeX commands for consistency

Improve SOC-OPF documentation

---

exp/sampler.jl

`exp/sampler.jl` now detects if there exists a `case.json` file (coming from `slurm/make_ref.jl`) containing a reference solution and if so, sets the time limit to `max(10 * reference solve time, 1 minute)`.
When the pipeline runs `slurm/make_ref.jl` (i.e., when generating `case.json`), there will be no time limit set. Since the jobs for the main solve don't get released until `make_ref` exits with success, they should all see the `case.json` file and set time limits appropriately.

Set time limit from reference solve

---

src/opf/ptdf.jl

ref https://discourse.julialang.org/t/duals-and-constraint-names-for-powermodels-and-infrastructuremodels/130311/4?u=klamike
All we ask of `F` is that it supports `F \ pg`

Relax LazyPTDF factorization type
